version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    volumes:
      - .:/app
    depends_on:
      - redis

